[package]
name = "lazy_type"
version = "0.1.0"
authors = ["3442853561 <3442853561@qq.com>"]
license = "MIT"
description = "A series of extension types"
keywords = ["type"]
repository = "https://github.com/3442853561/lazy_type"

[lib]
name = "lazy_type"
path = "src/lib.rs"

[[bin]]
name = "array"
path = "example/array.rs"
