[package]
name = "lazy_type"
version = "0.1.0"
authors = ["3442853561 <3442853561@qq.com>"]
license = "MIT"

[lib]
name = "lazy_type"
path = "src/lib.rs"

[[bin]]
name = "array"
path = "example/array.rs"
